# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "bin/release"
    - "README.md"
    - "spec/dummy/config/database.yml"
    - "spec/dummy/db/seeds.rb"

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
